# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 148659f05f61c05bba2c9eb8e0576c7edd4d161064464fb4a2179b03afe92cdff43460c682104ef2fc6e5aa60ee07d757bc9c39ae68e59f46b63ef71e07ec8f5

test:
  secret_key_base: ef9787a6f47835f2626a34628ee6ff026a54cbe7a186bcb8c069cc5b0f87f0d240e47a156c007c092e342a6a145016bafaaaa96a9b32fffefafe7a7423a136df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
